name: Backend Deployment

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.4.1'  # Adjust to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build backend (if necessary)
        run: npm run build  # Adjust build command if needed

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.BACKEND_PATH }}
            git pull origin main  # Update codebase
            npm ci --only=production  # Install dependencies
            pm2 restart 0  # Restart your Node.js app (using pm2 or similar)

      - name: Clean up
        run: npm prune --production
