name: Backend Deployment

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: self-hosted
    
    strategy: 
      matrix:
        node-version: [22.x]

    env:
      PORT: ${{ vars.PORT }}
      OUT_DIR: ${{ vars.OUT_DIR }}
      TEMP_DIR: ${{ vars.TEMP_DIR }}

      KROLL_BOND_LOGIN: ${{ vars.KROLL_BOND_LOGIN }}
      KROLL_BOND_PASS: ${{ vars.KROLL_BOND_PASS }}

      MOODYS_LOGIN: ${{ vars.MOODYS_LOGIN }}
      MOODYS_PASS: ${{ vars.MOODYS_PASS }}
      
      MORNING_STAR_LOGIN: ${{ vars.MORNING_STAR_LOGIN }}
      MORNING_STAR_PASS: ${{ MORNING_STAR_PASS }}

      AMBEST_LOGIN: ${{ vars.AMBEST_LOGIN }}
      AMBEST_PASS: ${{ vars.AMBEST_PASS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
            
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
 
      - name: Install dependencies
        run: npm install
        working-directory: ./ratings-history-express  # Adjust if your package.json is in a subdirectory

      - name: Build backend
        run: npm run build  # Adjust build command if needed
        working-directory: ./ratings-history-express  # Adjust if your build script is in a subdirectory

      - name: Clean up
        run: npm prune --production

      - name: Write environment variables to .env file
        run: |
          touch .env
          echo "PORT=${{ vars.PORT }}" >> .env
          echo "OUT_DIR=${{ vars.OUT_DIR }}" >> .env
          echo "TEMP_DIR=${{ vars.TEMP_DIR }}" >> .env
          echo "KROLL_BOND_LOGIN=${{ vars.KROLL_BOND_LOGIN }}" >> .env
          echo "KROLL_BOND_PASS=${{ vars.KROLL_BOND_PASS }}" >> .env
          echo "MOODYS_LOGIN=${{ vars.MOODYS_LOGIN }}" >> .env
          echo "MOODYS_PASS=${{ vars.MOODYS_PASS }}" >> .env
          echo "MORNING_STAR_LOGIN=${{ vars.MORNING_STAR_LOGIN }}" >> .env
          echo "MORNING_STAR_PASS=${{ vars.MORNING_STAR_PASS }}" >> .env
          echo "AMBEST_LOGIN=${{ vars.AMBEST_LOGIN }}" >> .env
          echo "AMBEST_PASS=${{ vars.AMBEST_PASS }}" >> .env
