name: Backend Deployment

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: self-hosted
    
    strategy: 
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
            
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
 
      - name: Install dependencies
        run: npm install
        working-directory: ./ratings-history-express  # Adjust if your package.json is in a subdirectory

      - name: Build
        run: npm run build

      - name: Build backend (if necessary)
        run: npm run build  # Adjust build command if needed
        working-directory: ./ratings-history  # Adjust if your build script is in a subdirectoryÏ

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/sibers/ratings-history-express/
            git pull origin main  # Update codebase
            npm ci --only=production  # Install dependencies
            pm2 restart 0  # Restart your Node.js app (using pm2 or similar)

      - name: Clean up
        run: npm prune --production
