name: Public Page Deployment

on:
  push:
    paths: 
    - ratings-history-public/**
    - .github/workflows/public.yml
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: self-hosted
    
    strategy: 
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
            
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean up
        run: npm prune --production

      - name: Restart express server
        run: pm2 restart public
